const messageBlock = [];
messageBlock.push("**message.author (Object, but prints as author.id):** " + message.author);
messageBlock.push("**message.author.createdAt:** " + message.author.createdAt);
messageBlock.push("**message.author.createdTimestamp:** " + message.author.createdTimestamp);
messageBlock.push("**message.author.defaultAvatarURL:** " + message.author.defaultAvatarURL);
messageBlock.push("**message.author.discriminator:** " + message.author.discriminator);
messageBlock.push("**message.author.flags:** " + message.author.flags);
messageBlock.push("**message.author.id:** " + message.author.id);
messageBlock.push("**message.author.lastMessage (Object, but prints as lastMessageID):** " + message.author.lastMessage);
messageBlock.push("**message.author.lastMessageChannelID:** " + message.author.lastMessageChannelID);
messageBlock.push("**message.author.lastMessageID:** " + message.author.lastMessageID);
messageBlock.push("**message.author.tag:** " + message.author.tag);
messageBlock.push("**message.author.username:** " + message.author.username);
messageBlock.push("**message.author.avatarURL():** " + message.author.avatarURL());
messageBlock.push("**message.author.displayAvatarURL():** " + message.author.displayAvatarURL());
messageBlock.push("**message.author.toString():** " + message.author.toString());

message.channel.send(messageBlock);

messageBlock.push("message.author: " + message.author);
messageBlock.push("\nmessage.author.avatar: " + message.author.avatar);
messageBlock.push("\nmessage.author.bot: " + message.author.bot);
messageBlock.push("\nmessage.author.client: " + message.author.client);
messageBlock.push("\nmessage.author.createdAt: " + message.author.createdAt);
messageBlock.push("\nmessage.author.createdTimestamp: " + message.author.createdTimestamp);
messageBlock.push("\nmessage.author.defaultAvatarURL: " + message.author.defaultAvatarURL);
messageBlock.push("\nmessage.author.discriminator: " + message.author.discriminator);
messageBlock.push("\nmessage.author.dmChannel: " + message.author.dmChannel);
messageBlock.push("\nmessage.author.flags: " + message.author.flags);
messageBlock.push("\nmessage.author.id: " + message.author.id);
messageBlock.push("\nmessage.author.lastMessage: " + message.author.lastMessage);
messageBlock.push("\nmessage.author.lastMessageChannelID: " + message.author.lastMessageChannelID);
messageBlock.push("\nmessage.author.lastMessageID: " + message.author.lastMessageID);
messageBlock.push("\nmessage.author.locale: " + message.author.locale);
messageBlock.push("\nmessage.author.partial: " + message.author.partial);
messageBlock.push("\nmessage.author.presence: " + message.author.presence);
messageBlock.push("\nmessage.author.system: " + message.author.system);
messageBlock.push("\nmessage.author.tag: " + message.author.tag);
messageBlock.push("\nmessage.author.username: " + message.author.username);
messageBlock.push("\nmessage.author.avatarURL(): " + message.author.avatarURL());
messageBlock.push("\nmessage.author.displayAvatarURL(): " + message.author.displayAvatarURL());
messageBlock.push("\nmessage.author.fetch(): " + message.author.fetch());
messageBlock.push("\nmessage.author.fetchFlags(): " + message.author.fetchFlags());
messageBlock.push("\nmessage.author.send(): " + message.author.send());
messageBlock.push("\nmessage.author.toString(): " + message.author.toString());